[project]
name = "llm-playground"
version = "0.1.0"
description = "My LLM playground"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "gradio>=5.45.0",
    "mlx-whisper>=0.4.2",
    "parakeet-mlx>=0.3.6",
]
